/**
 * module-store.js — Centralized animation module definitions & parameter store
 *
 * Each module represents an independent animation behavior with its own
 * enable/disable toggle and tunable parameters. The mock-driver reads
 * parameters from here on every tick, so slider changes take effect
 * immediately without restarting the token stream.
 *
 * CSS-affecting parameters (entrance scale/blur, pop scale) trigger
 * dynamic <style> regeneration when changed.
 */

// ── Module definitions ──────────────────────────────────────────────────

const MODULES = [
  {
    id: 'entrance',
    label: 'Entrance',
    enabled: true,
    params: [
      { key: 'entranceScale',    label: 'Scale',         min: 1.0, max: 2.5, step: 0.05, value: 1.35 },
      { key: 'entranceBlur',     label: 'Blur (px)',     min: 0,   max: 8,   step: 0.5,  value: 2 },
      { key: 'entranceDuration', label: 'Duration (ms)', min: 50,  max: 800, step: 25,   value: 350 },
    ],
  },
  {
    id: 'sympatheticPops',
    label: 'Sympathetic Pops',
    enabled: true,
    params: [
      { key: 'popCountMin',    label: 'Min Count',        min: 0,   max: 10,  step: 1,    value: 3 },
      { key: 'popCountMax',    label: 'Max Count',        min: 0,   max: 20,  step: 1,    value: 6 },
      { key: 'popScale',       label: 'Pop Scale',        min: 1.0, max: 1.5, step: 0.05, value: 1.15 },
      { key: 'popStaggerMin',  label: 'Stagger Min (ms)', min: 0,   max: 100, step: 5,    value: 20 },
      { key: 'popStaggerMax',  label: 'Stagger Max (ms)', min: 0,   max: 200, step: 5,    value: 50 },
    ],
  },
  {
    id: 'oscillation',
    label: 'Oscillation',
    enabled: true,
    params: [
      { key: 'oscillationSteps',    label: 'Steps',         min: 1,   max: 10, step: 1,    value: 4 },
      { key: 'stepMs',              label: 'Step (ms)',      min: 10,  max: 100, step: 5,   value: 35 },
      { key: 'oscillationAmpBase',  label: 'Amplitude',     min: 0.2, max: 4.0, step: 0.1, value: 1.6 },
      { key: 'oscillationAmpDecay', label: 'Amp Decay',     min: 0.1, max: 0.9, step: 0.05, value: 0.5 },
    ],
  },
  {
    id: 'disturbance',
    label: 'Disturbance',
    enabled: true,
    params: [
      { key: 'maxDisturbFraction', label: 'Max Fraction', min: 0.05, max: 1.0, step: 0.05, value: 0.35 },
      { key: 'nearbyWindow',       label: 'Nearby Window', min: 1,   max: 20,  step: 1,    value: 8 },
    ],
  },
  {
    id: 'stability',
    label: 'Stability',
    enabled: true,
    params: [
      { key: 'settleThreshold', label: 'Settle After (rounds)', min: 1,    max: 20,   step: 1,    value: 5 },
      { key: 'rippleChance',    label: 'Ripple Chance',          min: 0.0,  max: 0.2,  step: 0.005, value: 0.03 },
    ],
  },
  {
    id: 'axisCurve',
    label: 'Axis Curve',
    enabled: true,
    params: [
      { key: 'axisDecayCoeff',      label: 'Decay Coeff',     min: 0.0,  max: 0.1,  step: 0.005, value: 0.02 },
      { key: 'extremeBiasExponent', label: 'Bias Exponent',   min: 0.1,  max: 2.0,  step: 0.05,  value: 0.35 },
      { key: 'breathEvery',         label: 'Breath Every N',  min: 2,    max: 20,   step: 1,     value: 6 },
      { key: 'breathMultiplier',    label: 'Breath Mult',     min: 1.0,  max: 4.0,  step: 0.1,   value: 1.8 },
    ],
  },
];

// ── Runtime state ───────────────────────────────────────────────────────

// Fast lookup: key → current value
const paramValues = {};
// Fast lookup: moduleId → enabled
const moduleEnabled = {};

// Initialize from definitions
MODULES.forEach(mod => {
  moduleEnabled[mod.id] = mod.enabled;
  mod.params.forEach(p => {
    paramValues[p.key] = p.value;
  });
});

// ── Public API ──────────────────────────────────────────────────────────

export { MODULES };

export function getParam(key) {
  return paramValues[key];
}

export function setParam(key, value) {
  paramValues[key] = value;
}

export function isModuleEnabled(id) {
  return moduleEnabled[id] ?? true;
}

export function setModuleEnabled(id, enabled) {
  moduleEnabled[id] = enabled;
}

// ── CSS parameters (entrance & pop are CSS-driven) ──────────────────────

// Keys whose changes require CSS regeneration
const CSS_PARAM_KEYS = new Set([
  'entranceScale', 'entranceBlur', 'entranceDuration',
  'popScale',
]);

export function isCSSParam(key) {
  return CSS_PARAM_KEYS.has(key);
}

export function buildAnimationCSS() {
  const s = paramValues.entranceScale;
  const b = paramValues.entranceBlur;
  const d = paramValues.entranceDuration;
  const ps = paramValues.popScale;

  return `
/* Generated by module-store — do not edit manually */
.token.entering {
  opacity: 0;
  transform: scale(${s});
  filter: blur(${b}px);
}
.token.entered {
  opacity: 1;
  transform: scale(1);
  filter: blur(0);
  transition: opacity ${Math.round(d * 0.6)}ms ease-out,
              transform ${d}ms cubic-bezier(0.34, 1.56, 0.64, 1),
              filter ${Math.round(d * 0.7)}ms ease-out;
}
@keyframes sympathetic-pop {
  0%   { transform: scale(1);     filter: blur(0); }
  25%  { transform: scale(${ps}); filter: blur(1px); }
  100% { transform: scale(1);     filter: blur(0); }
}
.token.popping {
  animation: sympathetic-pop 350ms ease-out;
}
.token {
  transition: font-variation-settings 50ms linear;
}
`;
}

export function injectModuleCSS() {
  let el = document.getElementById('module-css');
  if (!el) {
    el = document.createElement('style');
    el.id = 'module-css';
    document.head.appendChild(el);
  }
  el.textContent = buildAnimationCSS();
}

// Inject initial CSS on module load
injectModuleCSS();
